import axios from "axios";
const api = axios.create({baseURL: import.meta.env.VITE_API_URL || "http://localhost:8000",headers:{"Content-Type":"application/json"}});
api.interceptors.request.use((config)=>{const token=localStorage.getItem("access_token");if(token) config.headers.Authorization=`Bearer ${token}`;return config;});
export const login=async(email,password)=>{const body=new URLSearchParams();body.append("username",email);body.append("password",password);const {data}=await api.post("/api/auth/login",body,{headers:{"Content-Type":"application/x-www-form-urlencoded"}});localStorage.setItem("access_token",data.access_token);return data;};
export const register=async(email,password)=>(await api.post("/api/auth/register",{email,password})).data;
export const requestPasswordReset=async(email)=>(await api.post("/api/auth/forgot-password",{email})).data;
export const resetPassword=async(token,password)=>(await api.post("/api/auth/reset-password",{token,password})).data;
export const getMe=async()=>(await api.get("/api/auth/me")).data;
export const getTransactions=async()=>(await api.get("/api/transactions/")).data;
export const createTransaction=async(payload)=>(await api.post("/api/transactions/",payload)).data;
export const updateTransaction=async(id,payload)=>(await api.put(`/api/transactions/${id}`,payload)).data;
export const deleteTransaction=async(id)=>(await api.delete(`/api/transactions/${id}`)).data;
export const getSummary=async()=>(await api.get("/api/dashboard/summary")).data;
export const getCategoriesLegacy=async()=>(await api.get("/api/dashboard/categories")).data;
export const getMonthly=async()=>(await api.get("/api/dashboard/monthly")).data;
export const getBudgets=async()=>(await api.get("/api/budgets")).data;
export const createBudget=async(payload)=>(await api.post("/api/budgets",payload)).data;
export const updateBudget=async(id,payload)=>(await api.put(`/api/budgets/${id}`,payload)).data;
export const deleteBudget=async(id)=>(await api.delete(`/api/budgets/${id}`)).data;
export const getBudgetAnalytics=async(month)=>(await api.get(`/api/budgets/analytics?month=${encodeURIComponent(month)}`)).data;
export const getCategoryTree=async(includeDisabled=false)=>(await api.get(`/api/categories?include_disabled=${includeDisabled}`)).data;
export const createCategory=async(payload)=>(await api.post("/api/categories",payload)).data;
export const updateCategory=async(id,payload)=>(await api.put(`/api/categories/${id}`,payload)).data;
export const deleteCategory=async(id)=>(await api.delete(`/api/categories/${id}`)).data;
export const createSubcategory=async(payload)=>(await api.post("/api/categories/subcategories",payload)).data;
export const updateSubcategory=async(id,payload)=>(await api.put(`/api/categories/subcategories/${id}`,payload)).data;
export const deleteSubcategory=async(id)=>(await api.delete(`/api/categories/subcategories/${id}`)).data;
export const logout=()=>localStorage.removeItem("access_token");
export default api;
export const getSavingsGoals=async()=>(await api.get('/api/savings-goals')).data;
export const createSavingsGoal=async(p)=>(await api.post('/api/savings-goals',p)).data;
export const updateSavingsGoal=async(id,p)=>(await api.put(`/api/savings-goals/${id}`,p)).data;
export const deleteSavingsGoal=async(id)=>(await api.delete(`/api/savings-goals/${id}`)).data;
export const getAccounts=async()=>(await api.get('/api/accounts')).data;
export const createAccount=async(p)=>(await api.post('/api/accounts',p)).data;
export const updateAccount=async(id,p)=>(await api.put(`/api/accounts/${id}`,p)).data;
export const deleteAccount=async(id)=>(await api.delete(`/api/accounts/${id}`)).data;
export const getRecurring=async()=>(await api.get('/api/recurring')).data;
export const createRecurring=async(p)=>(await api.post('/api/recurring',p)).data;
export const updateRecurring=async(id,p)=>(await api.put(`/api/recurring/${id}`,p)).data;
export const deleteRecurring=async(id)=>(await api.delete(`/api/recurring/${id}`)).data;
export const runRecurring=async(id)=>(await api.post(`/api/recurring/${id}/run`)).data;
export const getNotifications=async()=>(await api.get('/api/notifications')).data;
export const getAdvancedAnalytics=async()=>(await api.get('/api/analytics/advanced')).data;
export const getCalendar=async()=>(await api.get('/api/calendar')).data;
export const updateProfile=async(p)=>(await api.put('/api/profile',p)).data;
export const changePassword=async(p)=>(await api.post('/api/security/change-password',p)).data;
export const getSessions=async()=>(await api.get('/api/security/sessions')).data;
export const revokeAllSessions=async()=>(await api.post('/api/security/revoke-all')).data;
